- rpm/droid-config-h4113.spec
- sparse/usr/share/ssu/board-mappings.d/05-h4113.ini
Signed-off-by: Matti Kosola <matti.kosola@jolla.com>
> Add initial ssu config.

- sparse/etc/dconf/db/vendor.d/lipstick-configs.txt
XA2 doesn't seem to support hot-swap.
> Show reboot warning on SIM removal

- sparse/lib/systemd/system/droid-bootctl.service
- sparse/lib/systemd/system/graphical.target.wants/droid-bootctl.service
- sparse/usr/bin/droid/droid-bootctl.sh
Requires https://github.com/mer-hybris/hybris-boot/pull/146 and image built using hybris-sony-aosp-8.1.0_r35_20180714 manifest.
> [boot] Add systemd service to mark boot as successful. MER#1947

- sparse/etc/dconf/db/vendor.d/lipstick-configs.txt
- sparse/etc/dconf/db/vendor.d/silica-configs.txt
- sparse/lib/udev/rules.d/61-touchscreen.rules
- sparse/var/lib/environment/compositor/droid-hal-device.conf
These are the same values as f5121 except physicalDotsPerInch.
Please let me know if some need to be changed.
> [config] add lipstick and silica configs from f5121. also add /dev/touchscreen symlink. JB#42494

- kickstart/pack/h4113/hybris
Also picking busybox fixes into 3.0.2 too from submodule, omitting Juho’s HID commits.
> Tidyup 3.0.2

- patterns/jolla-configuration-h3113.yaml
- patterns/jolla-configuration-h3213.yaml
- patterns/jolla-configuration-h3413.yaml
- patterns/jolla-configuration-h4113.yaml
- patterns/jolla-configuration-h4213.yaml
- patterns/jolla-configuration-h4413.yaml
- patterns/jolla-hw-adaptation-discovery.yaml
- patterns/jolla-hw-adaptation-pioneer.yaml
- patterns/jolla-hw-adaptation-voyager.yaml
> Enable NFC

- sparse/boot/flash-on-windows.bat
- sparse/boot/flash.sh
Would also be great to have this in 3.0.2 to reduce "i looked for v17 but found v17B" requests to our care :)
> sw-binaries: note about revision letter in the archive file name

- droid-config-common.inc
> packaging: transition to apkd8

- sparse/boot/flash-on-windows.bat
- sparse/boot/flash.sh
Still need to confirm the exact version-baseband value and test on Windows :)
> make compatible only with previously flashed Android 8.1

- sparse/boot/flash-on-windows.bat
- sparse/boot/flash.sh
> flashing: allow also v16 blobs to be flashed

- sparse/boot/flash-on-windows.bat
- sparse/boot/flash.sh
Ready to be taken in, just as the https://github.com/mer-hybris/droid-config-sony-nile/pull/83 was
> flashing: allow also v16 blobs to be flashed (to upgrade-3.0.3)

- sparse/etc/mce/60-fingerprint-sensor-nile.conf
Signed-off-by: Matti Kosola <matti.kosola@jolla.com>
> Add mce config to wakeup fingerprint from supend.

- delete_file_h3113.list
- delete_file_h3213.list
- delete_file_h3413.list
- delete_file_h4113.list
- delete_file_h4213.list
- delete_file_h4413.list
- sparse/etc/dconf/db/vendor.d/jolla-camera-hw-discovery.txt
- make separate config with selfie flash/video torch enabled
- delete otherwise
> [camera] Enable front flash for discovery MER#2043

- sparse/usr/share/ssu/board-mappings.d/05-sony-nile.ini
[repos] Move to new alien feature model in RnD. JB#46366
Signed-off-by: Marko Saukko <marko.saukko@jolla.com>
> Move to another alien feature with Nile.

- sparse/etc/gst-droid/gstdroidcodec.conf
> [codec] Enable on-device h.265 decoding. JB#37780

- sparse/etc/ofono/ril_subscription.conf
- sparse/etc/ofono/ril_subscription.d/dual-sim.conf
- sparse/usr/libexec/droid-hybris/system/etc/init/ecclist.rc
Pull them from tmpfs files where they get written to by init
> Track emergency numbers provided by network

- kickstart/pack/h4113/hybris
- sparse/boot/flash-on-windows.bat
Modifers @DEVICES@ to support matching on supported devices and
changes the layout of the comment containing all supported devices as in flash.sh
> Support the check for product on Windows.

- droid-config-common.inc
- patterns/jolla-hw-adaptation-discovery.yaml
- patterns/jolla-hw-adaptation-pioneer.yaml
- patterns/jolla-hw-adaptation-voyager.yaml
[patterns] Replace audioflingeglue with audiosystem-passthrough. JB#50003
> patterns: Replace audioflingeglue with audiosystem-passthrough.

- patterns/jolla-hw-adaptation-discovery.yaml
- patterns/jolla-hw-adaptation-pioneer.yaml
- patterns/jolla-hw-adaptation-voyager.yaml
Requires these to be merged first:
mer-hybris/nfcd-mce-plugin#1
https://git.sailfishos.org/mer-core/nfcd/merge_requests/33
> patterns: Pull in nfcd-mce-plugin

- patterns/jolla-configuration-h3113.yaml
- patterns/jolla-configuration-h3213.yaml
- patterns/jolla-configuration-h3413.yaml
- patterns/jolla-configuration-h4113.yaml
- patterns/jolla-configuration-h4213.yaml
- patterns/jolla-configuration-h4413.yaml
- patterns/jolla-hw-adaptation-discovery.yaml
- patterns/jolla-hw-adaptation-pioneer.yaml
- patterns/jolla-hw-adaptation-voyager.yaml
It used to be a built-in plugin
> Pull in nfcd-dbuslog-plugin

- delete_file_h3113.list
- delete_file_h3213.list
- delete_file_h3413.list
- delete_file_h4113.list
- delete_file_h4213.list
- delete_file_h4413.list
- sparse/etc/mce/60-memnotify-nile-3gb.conf
- sparse/etc/mce/60-memnotify-nile-4gb.conf
Use 92% for critical and 88% for warning levels.
[configs] Add memnotify configuration. JB#54629
> configs: Add memnotify configuration.

- patterns/patterns-sailfish-device-adaptation-discovery.inc
- patterns/patterns-sailfish-device-adaptation-pioneer.inc
- patterns/patterns-sailfish-device-adaptation-voyager.inc
[patterns] Force hal package for sensors. JB#55245
> patterns: Force hal package for sensors.

- sparse/etc/appsupport.conf.d/20-nile.conf
[configs] Add config for appsupport system.img. JB#62435
> configs: add config for appsupport system.img
